### ISSUE TITLE
Was this issue resolved?

### ISSUE THREAD

**Issue by ccorcos** [schmidt/cordova-ios-iframe-example#1]

**Comment by schmidt** [comment]
[This](https://issues.apache.org/jira/browse/CB-10324) is the bug ticket in cordova-ios. It wasn't solved and merely considered a missing feature. See the ticket comments for details.

I think, I've worked around the problem back then using the `<allow-navigation href="https:*" />` directive.

**Comment by ccorcos** [comment]
Hmm. I still cant get iframes working :( Thanks though.

**Comment by schmidt** [comment]
Did you try to white list `about:blank`? [[issue comment](https://issues.apache.org/jira/browse/CB-10324?focusedCommentId=15093811&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15093811)]

**Comment by ccorcos** [comment]
I have everything opened up:

```
<access origin="*" />
<allow-navigation href="*" />
<allow-intent href="*" />
```

I have no CSP which I think defaults to leaving everything open.

I also have this plugin installed just because I'm trying things: https://github.com/leecrossley/cordova-plugin-transport-security

**Comment by schmidt** [comment]
Well, the `about:blank` part was my last idea. I haven't worked with cordova since early 2016. So I cannot give you any further advice, than to check the logs.

Good luck.

**Comment by ccorcos** [comment]
Alright, thanks anyways though!
